### ISSUE TITLE
[Major] Hamburger Menu is not responsive

### ISSUE THREAD

**Issue by meghajain2** [info442-aut21/f-team#84] opened 2021-11-22 17:50 UTC
For mobile devices, the navbar goes from normal to within a hamburger menu. When I tried to click on the menu, it was not responsive and the nav links were not showing up.

Environment: Chrome Version 96.0.4664.55 on MacOS Big Sur
Steps to reproduce: Change the responsive screen size to a smaller device, click on the hamburger menu
Expected result: Show a drop-down list of all the nav tabs there are for the website
Actual result: When you click on the hamburger menu, nothing happens

**Comment by Skylitmoon** [comment] 2021-11-24 17:46
Duplicate of https://github.com/info442-aut21/f-team/issues/60

**Closed by Skylitmoon** 2021-11-24 17:46 UTC
Labels: bug, duplicate
