### ISSUE TITLE
[Major] No way to get back to the site after clicking on a recipe link

### ISSUE THREAD

**Issue by Vivianngu3** [info442-aut21/f-team#68] opened 2021-11-22 17:19 UTC
![Screen Shot 2021-11-22 at 9 18 19 AM](https://user-images.githubusercontent.com/62910701/142906151-6cd039fa-c2dc-4aa4-8b58-e5eb214565f6.png)

**Comment by Vivianngu3** [comment] 2021-11-22 17:54
Description: When going to a recipe link and then trying to go back to the site there is a 404 error.
Encountered: Chrome v90.0.4430.85 
Steps to Reproduce: Click 'Main Page', Click 'Go to Recipe', click back button on browser
Expected Results: To go back to the original site
Actual Results: 404 page

**Comment by Skylitmoon** [comment] 2021-11-24 17:10
This issue is a duplicate of [66](https://github.com/info442-aut21/f-team/issues/66)

**Closed by Skylitmoon** 2021-11-24 17:10 UTC
Labels: bug

**Comment by cherimarie** [comment] 2021-11-29 17:26
For grading purposes, I won't count this as a duplicate as it was created only one minute after the original, so I don't think Vivian could have seen the original.
